### ISSUE TITLE
I don't have write access to the repo, i can't add stuff

### ISSUE THREAD

**Issue by capturetheworld** [GaelForceRoboticsClub/laser-harp#1]

**Comment by ghost** [comment]
Did you fork the repo?

**Comment by capturetheworld** [comment]
Yea, I can fork it and clone it but I can't push to it. You have to add me as a collaborator or I have to do a pull request every time

**Comment by DevinMui** [comment]
holy ***\* you guys. spamming my email.

**Comment by capturetheworld** [comment]
Devin wat are you doing here? I am still not added as a collaborator. Could you add me and James as an Admin for the org?
